---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/8/31 15:52
---
--定义一个应用程序公有的Lua对象app_info
local app_info = {version = "0.1.0"}
--增加一个path属性，保存Nginx进程所保存的Lua模块路径，包括conf文件配置的部分路径
app_info.path = package.path

--局部函数,取得最大值
local function max(num1,num2)
    if num1 > num2 then
        result = num1;
    else
        result = num2;
    end
    return result;
end
--统一的模块对象
local _Module = {
    app_info = app_info;
    max = max;
}
return _Module