---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/8/31 17:03
---
local function showDataType()
    local i;
    basic.log("字符串的类型", type("hello world"))
    basic.log("方法的类型", type(showDataType))
    basic.log("true的类型", type(true))
    basic.log("整数数字的类型", type(360))
    basic.log("浮点数字的类型", type(360.0))
    basic.log("nil值的类型", type(nil))
    basic.log("未赋值变量i的类型", type(i))
end

--统一的模块对象
local _Module = {
    showDataType = showDataType;
}
return _Module