---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/8/31 15:57
---
--- 启动调试
local mobdebug = require("luaScript.initial.mobdebug")
mobdebug.start();
--导入自定义的模块
local basic = require("luaScript.module.common.basic");
--使用模块的成员属性
ngx.say("Lua path is :" .. basic.app_info.path)
ngx.say("<br>");
--使用模块的成员方法
ngx.say("max 1 and 11 is:" .. basic.max(1,11));