---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2023/8/31 17:04
---
--- 启动调试
local mobdebug = require("luaScript.initial.mobdebug")
mobdebug.start();
--导入自定义的基础模块
local basic = require("luaScript.module.common.basic")
--导入自定义的dataType模块
local dataType = require("luaScript.module.demo.dataType")
ngx.say("下面是数据类型演示的结果输出：<br>")
dataType.showDataType();